import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from "@/components/Layout";
import {Swiper, SwiperSlide} from "swiper/react";
import {Pagination,Autoplay, Navigation} from "swiper";
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";

const inter = Inter({subsets: ['latin']})

export default function Home() {

    const tableData = [
        {
            name: 'Roblox',
            users: 1234,
            price: 1234,
        },
        {
            name: 'McDonalds',
            users: 1234,
            price: 1234,
        },
        {
            name: 'SandBox',
            users: 1234,
            price: 1234,
        },
        {
            name: 'Meta',
            users: 1234,
            price: 1234,
        },
        {
            name: 'Hive',
            users: 1234,
            price: 1234,
        },
    ]


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout title={'Add new Metaverse'}>
                <div className={'flex items-center w-[700px]'}>
                    <div className={'flex flex-col items-center'}>
                        <p className={'font-bold text-white text-2xl mb-3'}>Your asset</p>
                        <div className={'w-60 aspect-square relative'}>
                            <Image src={'/images/robl1.png'} alt={'robl1'} layout={'fill'}
                                   className={'rounded-xl'}></Image>
                        </div>
                    </div>
                    <div className={'w-60 h-12 relative'}>
                        <Image src={'/images/icons/arrow.svg'} alt={'arrow'} layout={'fill'} className={''}></Image>
                    </div>
                    <div className={'flex flex-col items-center'}>
                        <p className={'font-bold text-white text-2xl mb-3'}>Your asset in Roblox</p>
                        <div className={'w-60 aspect-square relative'}>
                            <Image src={'/images/robl2.png'} alt={'robl2'} layout={'fill'}
                                   className={'rounded-xl'}></Image>
                        </div>
                    </div>
                </div>
                <div className={'w-[700px] mt-4 flex items-center justify-around'}>
                    <button
                        className={'blue-button w-48 h-12 text-xl border-2 border-white text-white font-bold mt-4'}>Upgrade
                        1 asset
                    </button>
                    <button
                        className={'blue-button w-48 h-12 text-xl border-2 border-white text-white font-bold mt-4'}>Upgrade
                        all
                    </button>
                </div>
                <div className={'w-[700px] mt-20 flex flex-wrap justify-center'}>
                    <p className={'font-bold text-white text-2xl mb-5'}>Styles in metaverse</p>
                    <div className={'w-full'}>
                        <Swiper
                            slidesPerView={3}
                            spaceBetween={30}
                            className="mySwiper"
                            modules={[Autoplay,Navigation]}
                            navigation={true}
                            autoplay={{
                                delay: 1500,
                                disableOnInteraction: false,
                            }}
                        >
                            <SwiperSlide
                                className={'w-full flex items-center justify-center aspect-square relative'}><Image
                                src={'/images/metaverses/slide1.png'} alt={'1'} layout={'fill'}
                                className={'object-cover rounded-xl'}></Image> </SwiperSlide>
                            <SwiperSlide
                                className={'w-full flex items-center justify-center aspect-square relative'}><Image
                                src={'/images/metaverses/slide2.jpg'} alt={'2'} layout={'fill'}
                                className={'object-cover rounded-xl'}></Image> </SwiperSlide>
                            <SwiperSlide
                                className={'w-full flex items-center justify-center aspect-square relative'}><Image
                                src={'/images/metaverses/slide3.jpg'} alt={'3'} layout={'fill'}
                                className={'object-cover rounded-xl'}></Image> </SwiperSlide>
                            <SwiperSlide
                                className={'w-full flex items-center justify-center aspect-square relative'}><Image
                                src={'/images/metaverses/slide4.gif'} alt={'4'} layout={'fill'}
                                className={'object-cover rounded-xl'}></Image> </SwiperSlide>
                            <SwiperSlide
                                className={'w-full flex items-center justify-center aspect-square relative'}><Image
                                src={'/images/metaverses/slide5.jpg'} alt={'5'} layout={'fill'}
                                className={'object-cover rounded-xl'}></Image> </SwiperSlide>
                            <SwiperSlide
                                className={'w-full flex items-center justify-center aspect-square relative'}><Image
                                src={'/images/metaverses/slide6.jpg'} alt={'6'} layout={'fill'}
                                className={'object-cover rounded-xl'}></Image> </SwiperSlide>

                        </Swiper>
                    </div>
                </div>
            </Layout>
        </>
    )
}
